using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PortoSeguroBOT.Helpers
{
    public class ConstantsPais
    {
        public static readonly Pais[] PAISES = new Pais[]
        {
             new Pais("Afeganistão", 1, 2),
             new Pais("África do Sul", 2, 1),
             new Pais("Albânia", 3, 3),
             new Pais("Alemanha", 211, 3),
             new Pais("Andorra", 4, 3),
             new Pais("Angola", 5, 1),
             new Pais("Anguilla", 6, 4),
             new Pais("Antígua e Barbuda", 8, 4),
             new Pais("Antilhas Holandesas", 9, 4),
             new Pais("Arábia Saudita", 10, 2),
             new Pais("Argélia", 11, 1),
             new Pais("Argentina", 12, 4),
             new Pais("Armênia", 13, 2),
             new Pais("Aruba", 14, 4),
             new Pais("Austrália", 15, 5),
             new Pais("Áustria", 212, 3),
             new Pais("Azerbaijão", 16, 2),
             new Pais("Bahamas", 17, 4),
             new Pais("Bahrein", 18, 2),
             new Pais("Bangladesh", 19, 2),
             new Pais("Barbados", 20, 4),
             new Pais("Bielorrússia", 21, 3),
             new Pais("Bélgica", 213, 3),
             new Pais("Belize", 22, 4),
             new Pais("Benin", 23, 1),
             new Pais("Bermudas", 24, 4),
             new Pais("Bolívia", 25, 4),
             new Pais("Bósnia - Herzegovina", 26, 3),
             new Pais("Botsuana", 27, 1),
             new Pais("Brasil", 28, 4),
             new Pais("Brunei", 29, 2),
             new Pais("Bulgária", 30, 3),
             new Pais("Burkina Fasso", 31, 1),
             new Pais("Burundi", 32, 1),
             new Pais("Butão", 33, 2),
             new Pais("Cabo Verde", 34, 1),
             new Pais("Camarões", 35, 1),
             new Pais("Camboja", 36, 2),
             new Pais("Canadá", 37, 4),
             new Pais("Cazaquistão", 38, 2),
             new Pais("Chade", 39, 1),
             new Pais("Chile", 40, 4),
             new Pais("China", 41, 2),
             new Pais("Chipre", 42, 2),
             new Pais("Cingapura", 43, 2),
             new Pais("Colômbia", 44, 4),
             new Pais("Congo", 45, 1),
             new Pais("Coréia do norte", 46, 2),
             new Pais("Coréia do sul", 47, 2),
             new Pais("Costa do Marfim", 48, 1),
             new Pais("Costa Rica", 49, 4),
             new Pais("Croácia", 50, 3),
             new Pais("Cuba", 51, 4),
             new Pais("Djibouti", 52, 1),
             new Pais("Dinamarca", 214, 3),
             new Pais("Dominica", 53, 4),
             new Pais("Egito", 54, 1),
             new Pais("El Salvador", 55, 4),
             new Pais("Emirados Árabes", 56, 2),
             new Pais("Equador", 57, 4),
             new Pais("Eritréia", 58, 1),
             new Pais("Escócia", 162, 3),
             new Pais("Eslováquia", 215, 3),
             new Pais("Eslovênia", 216, 3),
             new Pais("Espanha", 217, 3),
             new Pais("Estados Unidos", 59, 4),
             new Pais("Estônia", 218, 3),
             new Pais("Etiópia", 60, 1),
             new Pais("Fiji", 61, 5),
             new Pais("Filipinas", 62, 5),
             new Pais("Finlândia", 219, 3),
             new Pais("França", 220, 3),
             new Pais("Gabão", 63, 1),
             new Pais("Gâmbia", 64, 1),
             new Pais("Gana", 65, 1),
             new Pais("Geórgia do Sul e Ilhas Sandwich", 66, 6),
             new Pais("Geórgia", 67, 2),
             new Pais("Gibraltar", 68, 3),
             new Pais("Granada", 69, 4),
             new Pais("Grécia", 221, 3),
             new Pais("Groelândia", 70, 4),
             new Pais("Guadalupe", 71, 4),
             new Pais("Guam", 72, 5),
             new Pais("Guatemala", 73, 4),
             new Pais("Guiana", 74, 4),
             new Pais("Guiana Francesa", 75, 4),
             new Pais("Guiné", 76, 1),
             new Pais("Guiné-Bissau", 77, 1),
             new Pais("Guiné Equatorial", 78, 1),
             new Pais("Holanda", 222, 3),
             new Pais("Honduras", 80, 4),
             new Pais("Hong Kong", 81, 1),
             new Pais("Hungria", 223, 3),
             new Pais("Iêmen", 82, 2),
             new Pais("Ilha Bouvet", 83, 6),
             new Pais("Ilha Heard e Ilhas McDonald", 84, 6),
             new Pais("Ilha Natal", 85, 2),
             new Pais("Ilha Norfolk", 86, 6),
             new Pais("Ilha Pitcairn", 87, 6),
             new Pais("Ilha Reunião", 88, 3),
             new Pais("Ilhas Cayman", 89, 4),
             new Pais("Ilhas Cocos", 90, 2),
             new Pais("Ilhas Comores", 91, 1),
             new Pais("Ilhas Cook", 92, 5),
             new Pais("Ilhas Faeroes", 93, 3),
             new Pais("Ilhas Falklands (Malvinas)", 94, 4),
             new Pais("Ilhas Marianas do Norte", 95, 1),
             new Pais("Ilhas Marshall", 96, 5),
             new Pais("Ilhas Salomão", 97, 5),
             new Pais("Ilhas Seychelles", 98, 1),
             new Pais("Ilhas Tokelau", 99, 5),
             new Pais("Ilhas Turcas e Caicos", 100, 4),
             new Pais("Ilhas Virgens Britânicas", 101, 4),
             new Pais("Ilhas Virgens dos Estados Unidos", 102, 4),
             new Pais("Ilhas Wallis e Futuna", 103, 5),
             new Pais("Inglaterra", 162, 3),
             new Pais("Índia", 104, 2),
             new Pais("Indonésia", 105, 2),
             new Pais("Irã", 106, 2),
             new Pais("Iraque", 107, 2),
             new Pais("Irlanda", 224, 3),
             new Pais("Irlanda do Norte", 162, 3),
             new Pais("Israel", 108, 2),
             new Pais("Islândia", 225, 3),
             new Pais("Itália", 225, 3),
             new Pais("Iugoslávia", 109, 3),
             new Pais("Jamaica", 110, 4),
             new Pais("Japão", 111, 2),
             new Pais("Jordânia", 112, 2),
             new Pais("Quênia", 113, 1),
             new Pais("Quirguistão", 114, 2),
             new Pais("Kiribati", 115, 5),
             new Pais("Kuwait", 116, 2),
             new Pais("Laos", 117, 2),
             new Pais("Lesoto", 118, 1),
             new Pais("Letônia", 227, 3),
             new Pais("Líbano", 119, 2),
             new Pais("Libéria", 120, 1),
             new Pais("Líbia", 121, 1),
             new Pais("Liechtenstein", 122, 3),
             new Pais("Lituânia", 228, 3),
             new Pais("Luxemburgo", 229, 3),
             new Pais("Macau", 123, 2),
             new Pais("Macedônia", 124, 2),
             new Pais("Madagascar", 125, 1),
             new Pais("Malásia", 126, 2),
             new Pais("Malaui", 127, 1),
             new Pais("Maldivas", 128, 2),
             new Pais("Mali", 129, 1),
             new Pais("Malta", 230, 3),
             new Pais("Marrocos", 130, 1),
             new Pais("Martinica", 131, 4),
             new Pais("Mauricio", 132, 1),
             new Pais("Mauritânia", 133, 1),
             new Pais("Mayotte", 134, 1),
             new Pais("México", 135, 4),
             new Pais("Micronésia", 136, 5),
             new Pais("Moçambique", 137, 1),
             new Pais("Moldávia", 138, 3),
             new Pais("Mônaco", 139, 3),
             new Pais("Mongólia", 140, 2),
             new Pais("Montserrat", 141, 4),
             new Pais("Namíbia", 142, 1),
             new Pais("Nauru", 143, 5),
             new Pais("Nepal", 144, 2),
             new Pais("Nicarágua", 145, 4),
             new Pais("Niger", 146, 1),
             new Pais("Nigéria", 147, 1),
             new Pais("Niue", 148, 5),
             new Pais("Noruega", 231, 3),
             new Pais("Nova Caledônia", 149, 5),
             new Pais("Nova Zelândia", 150, 5),
             new Pais("Omã", 151, 2),
             new Pais("Outras Ilhas menores dos EUA", 152, 4),
             new Pais("País de Gales", 162, 3),
             new Pais("Paquistão", 153, 1),
             new Pais("Palau", 154, 5),
             new Pais("Panamá", 155, 4),
             new Pais("Papua-Nova Guiné", 156, 5),
             new Pais("Paraguai", 157, 4),
             new Pais("Peru", 158, 4),
             new Pais("Polinésia Francesa", 159, 5),
             new Pais("Polônia", 232, 3),
             new Pais("Porto Rico", 160, 4),
             new Pais("Portugal", 233, 3),
             new Pais("Qatar", 161, 2),
             new Pais("República Centro Africana", 163, 1),
             new Pais("República Democrática do Congo", 164, 1),
             new Pais("República Dominicana", 165, 4),
             new Pais("República Tcheca", 234, 3),
             new Pais("Romênia", 166, 3),
             new Pais("Ruanda", 167, 1),
             new Pais("Rússia", 168, 3),
             new Pais("Saara Ocidental", 169, 1),
             new Pais("Saint-Pierre e Miquelon", 170, 4),
             new Pais("Samoa Ocidental", 171, 5),
             new Pais("Samoa Americana", 172, 5),
             new Pais("San Marino", 173, 3),
             new Pais("Santa Helena", 174, 1),
             new Pais("Santa Lúcia", 175, 4),
             new Pais("São Cristóvão e Nevis", 176, 4),
             new Pais("São Tomé e Príncipe", 177, 1),
             new Pais("São Vicente e Granadinas", 178, 4),
             new Pais("Senegal", 179, 1),
             new Pais("Serra Leoa", 180, 1),
             new Pais("Síria", 181, 2),
             new Pais("Somália", 182, 1),
             new Pais("Sri Lanka", 183, 2),
             new Pais("Suazilândia", 184, 1),
             new Pais("Sudão", 185, 1),
             new Pais("Suécia", 235, 3),
             new Pais("Suíça", 236, 3),
             new Pais("Suriname", 186, 4),
             new Pais("Svalbard e Jan Mayen", 187, 3),
             new Pais("Tadjiquistão", 188, 2),
             new Pais("Tailândia", 189, 2),
             new Pais("Taiwan", 190, 2),
             new Pais("Tanzânia", 191, 1),
             new Pais("Terras Austrais Francesas", 192, 6),
             new Pais("Território Britânico do Oceano Índico", 193, 2),
             new Pais("Timor-Leste", 194, 2),
             new Pais("Togo", 195, 1),
             new Pais("Tonga", 196, 5),
             new Pais("Trinidad e Tobago", 197, 4),
             new Pais("Tunísia", 198, 1),
             new Pais("Turquia", 199, 2),
             new Pais("Tuvalu", 200, 5),
             new Pais("Ucrânia", 201, 3),
             new Pais("Uganda", 202, 1),
             new Pais("Uruguai", 203, 4),
             new Pais("Uzbequistão", 204, 2),
             new Pais("Vanuatu", 205, 5),
             new Pais("Vaticano", 206, 3),
             new Pais("Venezuela", 207, 4),
             new Pais("Vietnã", 208, 2),
             new Pais("Zâmbia", 209, 1),
             new Pais("Zimbábue", 210, 1)
        };

        public class Pais
        {
            //TODO arrumar get set
            public string Descricao { get; set; }
            public int CodigoPais { get; set; }
            public int CodigoContinente { get; set; }

            public Pais(string Descricao, int CodigoPais, int CodigoContinente)
            {
                this.Descricao = Descricao;
                this.CodigoPais = CodigoPais;
                this.CodigoContinente = CodigoContinente;
            }
        }
    }
}